name: Expose Secret

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Secret echo
        run: |
          echo "My secret is: ${{ secrets.TEST_SECRET }}"
